- server/build.gradle
- server/src/main/java/com/mainproject/doctor/controller/DoctorController.java
- server/src/main/java/com/mainproject/doctor/dto/DoctorDto.java
- server/src/main/java/com/mainproject/doctor/mapper/DoctorMapper.java
- server/src/main/java/com/mainproject/doctor/repository/DoctorRepository.java
- server/src/main/java/com/mainproject/doctor/service/DoctorService.java
- server/src/main/java/com/mainproject/global/dto/LoginDto.java
- server/src/main/java/com/mainproject/member/controller/MemberController.java
- server/src/main/java/com/mainproject/member/dto/MemberDto.java
- server/src/main/java/com/mainproject/member/entity/Member.java
- server/src/main/java/com/mainproject/member/mapper/MemberMapper.java
- server/src/main/java/com/mainproject/member/repository/MemberRepository.java
- server/src/main/java/com/mainproject/member/service/MemberService.java
보안을 제외한 기본적인 기능 구현 완료했고 주석으로 추가할 부분 표시 완료
보고 확인 부탁드립니다!
> [feat] 의사, 회원 Entity, Service, Dto, Mapper, Repository, Controller 초안 구현   

- client/src/App.js
- client/src/Components/Header/Header.jsx
- client/src/Pages/DoctorSignup/DoctorSignup.jsx
- client/src/Pages/DoctorSignup/Doctorsignup.jsx
- client/src/Pages/Login/Login.jsx
- client/src/Pages/Signup/Signup.jsx
- client/src/Style/DoctorSignupStyle.js
- client/src/Style/HeaderStyle.js
- client/src/Style/SignupStyle.js
- 일반 회원가입 페이지 : 화면 구현 및 유효성 검사 추가
🚨 App.js 수정 있습니다!
> Fe/songa to dev : 일반 회원가입 페이지 - 화면 구현 및 유효성 검사 추가

- client/data.json
- client/src/App.js
- client/src/Components/Header/Header.jsx
- client/src/Pages/DoctorSignup/DoctorSignup.jsx
- client/src/Pages/Login/Login.jsx
- client/src/Pages/Signup/Signup.jsx
- client/src/Style/HeaderStyle.js
- Login 페이지 : Axios  test 코드 작성
- 일반 회원가입 페이지 : Axios  test 코드 작성, 이용약관 유효성 검사 추가
- 의사 회원가입 페이지 : Axios  test 코드 작성, 이용약관 유효성 검사 추가
🚨 App.js, data.json 수정 있습니다!
> Fe/songa to dev : Login, 일반 회원가입, 의사 회원가입-Axios  test 코드 작성, 이용약관 유효성 검사 추가

- client/src/App.js
- client/src/Components/AskForm/LocationInput.jsx
- client/src/Components/AskForm/TextEditor.jsx
- client/src/Components/AskForm/TypeInput.jsx
- client/src/Components/MakeContents/MakeContents.jsx
- client/src/Components/Nav/Nav.jsx
- client/src/Components/ReportModal/ReportModal.jsx
- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- client/src/Style/AskQuestionStyle.js
- client/src/Style/MakeContentStyle.js
- client/src/Style/NavStyle.js
- client/src/Style/QuestionDetailStyle.js
- client/src/Style/ReportModalStyle.js
- client/src/Style/ReviewDetailStyle.js
- client/src/Style/ReviewModalStlye.js
* confirm()을 이용하여 답변 채택, 게시글 수정, 삭제 틀만 구현했습니다.
* react-quill 사용 시 발생하는 defaultValue 오류 수정을 위해서 TextEditor.jsx 파일 내 select 태그에 defaultValue element를  넣어주었고,  그에 맞게 option 태그 내 selected element를 삭제하고 value값을 넣어주었습니다.
* 질문 및 리뷰 상세페이지  사용을 위해서 App.js에서  Route 2개 추가하였습니다(추후에 삭제할 예정입니다.)
> Fe/seungmin to Dev : 리뷰 상세 페이지 간단하게 답변 채택, 게시글 수정,삭제 로직 구현

- client/package-lock.json
- client/package.json
- client/src/Pages/Landing/Landing.jsx
- client/src/Style/OfferInfoStyle.js
- client/src/util/useScrollFadeIn.js
- Landing 페이지 - OfferInfo 컴포넌트 구현
- scrollFadein Hook 구현 및 적용 
🚨 package-json 수정 : react-intersection-observer 라이브러리 추가 설치 했습니다~!
[OfferInfo 컴포넌트 구현 모습]
> Fe/songa to dev : Landing 페이지 - OfferInfo 컴포넌트 구현 및 scrollFadein Hook 구현 및 적용 

- client/src/App.js
dev 땡겨보니까 경로 오류 발생해서 자잘한 PR 남깁니다~!
> style:App.js-경로 수정

- server/src/main/java/com/mainproject/comment/entity/CommentLike.java
- server/src/main/java/com/mainproject/comment/repository/CommentLikeRepository.java
- server/src/main/java/com/mainproject/global/dto/PrincipalDto.java
- server/src/main/java/com/mainproject/global/exception/ExceptionCode.java
- server/src/main/java/com/mainproject/member/controller/DoctorController.java
- server/src/main/java/com/mainproject/member/service/MemberService.java
- server/src/main/java/com/mainproject/post/entity/PostLike.java
- server/src/main/java/com/mainproject/post/repository/PostLikeRepository.java
- server/src/main/java/com/mainproject/post/service/PostService.java
1. 회원 service 클래스에 로그인정보 검증하는 로직 추가
2. 의사 controller 클래스에 의사 조회하는 로직 추가
3. 게시글과 댓글 좋아요 기능 구현 위한 entity와 repository 추가
(나머지 좋아요 기능은 테스트 서버에 구현 완료했습니다. 게시글이랑 댓글 crud 완성 되면 한번 병합 한번 하고 제가 코드 옮긴 후에 다시 피알 날리는 걸로 하겠습니다.)
> [feat] 좋아요 테이블, 회원 로그인 검증 기능 추가

- client/src/Components/ReviewForm/HospitalInput.jsx
- client/src/Pages/Review/Review.jsx
- client/src/Style/AskQuestionStyle.js
> FE/Seungmin to Dev : 리뷰 작성 시 병원명 입력을 위한 input tag 생성

- client/public/index.html
- client/src/Components/CommentForm/CommentForm.jsx
- client/src/Components/HospitalLocation/HospitalLocation.jsx
- client/src/Style/ServiceInfoStyle.js
- HospitalLocation 컴포넌트 - 로직 구현
- CommentForm 컴포넌트 - 댓글 작성 폼 구현
kakao map API 사용을 위해 index.html에 script 구문 추가 되었습니다.
HospitalLocation, CommentForm 컴포넌트는 아직 리뷰 상세 페이지에 안에 추가하지는 않았습니다.
HospitalLocation는 로컬에서 .env에 kakao api key 주소 설정 필요합니다~! 
[HospitalLocation 컴포넌트 구현 모습]
받아오게 될 병원명 + 서울 위도, 경도로 지도를 나타낸 모습
[CommentForm 컴포넌트]
> Fe/songa to dev : Hospital Location 컴포넌트, CommentForm 컴포넌트 구현

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/Components/UserInfo/UserCardProfile.jsx
- client/src/Style/UserCardProfileStyle.js
- client/src/Style/UserMainProfileStyle.js
##Modal
1. 모달창이 뜨면 스크롤이 불가능하고 창을 반드시 컨트롤 해야 다음 작업을 할 수 있음.
2. 회원탈퇴 확인시 랜딩페이지로 이동.
##LogOut
1. 로그아웃 버튼 클릭시 랜딩페이지로 이동.
> FE/JongWoo to dev: UserInfo 회원탈퇴 및 로그아웃 Modal/navigate 기능 작업

- client/package.json
- client/src/Pages/DoctorSignup/DoctorSignup.jsx
- client/src/Pages/Login/Login.jsx
- client/src/Pages/Signup/Signup.jsx
- client/src/atoms/atoms.js
- client/src/index.js
- 일반회원, 의사 회원 Sign up 페이지-post 요청 성공 확인
- loginState atom 생성
- universal-cookie 라이브러리 설치
- Login- post 요청 성공 확인 및 1차 작성
> Fe/songa  to dev

- client/package.json
- client/src/Pages/Login/Login.jsx
- client/src/atoms/atoms.js
- chore : recoil-persist 라이브러리 설치
- fix : 새로 고침 시 로그인, 유저 정보 상태 유지 코드 추가
> [FE] chore : recoil-persist 라이브러리 설치

- client/src/Components/AskForm/PostData.jsx
- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/Review/Review.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
* 로그인 상태관리를 이용하여 페이지 내 권한 부여
* 서버와 직접 통신하여 리뷰 및 질문 작성 기능 구현
* 조회 부분의 end포인트는 직접 변경 부탁드립니다.
* 너무 정신이 없어서 매끄럽지 못한 코드는 이해 부탁드립니다
> Fe/seungmin -> dev : 로그인 상태관리를 이용하여 페이지 내 권한 부여, 서버와 직접 통신하여 리뷰 및 질문 작성 기능 구현

- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/Review/Review.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- client/src/Style/QuestionDetailStyle.js
* 리뷰/질문 좋아요 기능 추가
* 리뷰 페이지 별점 항목 추가
* nav 컴포넌트 라우터 경로 수정
* 신고 사유 탬플릿 생성 및 스타일 수정
> Fe/seungmin to Dev 

- client/package-lock.json
- client/package.json
- client/src/Components/Nav/Nav.jsx
- client/src/Components/ReportModal/ReportModal.jsx
- client/src/Components/ReportModal/ReviewReason.jsx
- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Style/ReportModalStyle.js
* 이전 merge에서 누락 파일들 다시 commit 올려서 merge 합니다.
> fix: commit 누락 파일 수정

- client/src/App.js
- client/src/Components/DoctorSignup/DoctorRegiInfoModal.jsx
- client/src/Components/Header/Header.jsx
- client/src/Components/Loading/Loading.jsx
- client/src/Pages/DoctorSignup/DoctorSignup.jsx
- client/src/Pages/Landing/Landing.jsx
- client/src/Pages/Login/Login.jsx
- client/src/Pages/Signup/Signup.jsx
- client/src/Style/DoctorSignupStyle.js
- client/src/Style/GreetingInfo.js
- client/src/Style/HeaderStyle.js
- client/src/Style/LoginStyle.js
- client/src/Style/SignupStyle.js
- client/src/index.js
- client/src/util/useDidMountEffect.js
- client/src/variables.css
- refactor : React.lazy 와 Suspense 함수 적용
- Loading 컴포넌트 구현
- fix : antd message 사용 시 useEffect 사용 요청 에러 헤결
> refactor : React.lazy 와 Suspense 함수 적용

- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- style : 오탈자 수정
- fix : Cannot read properties of undefined error 해결
> [FE] fix : Cannot read properties of undefined error 해결 

- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
fix:질문, 리뷰 게시글 좋아요 기능 구현 #51 #60
> [FE] fix:질문, 리뷰 게시글 좋아요 기능 구현

- client/package-lock.json
- client/package.json
- client/public/index.html
- client/src/Components/Section/PostList.jsx
- client/src/Components/Section/PostPagination.jsx
- client/src/Components/Section/PostSearch.jsx
- client/src/Components/UserInfo/UserCardProfile.jsx
- client/src/Components/UserInfo/UserMainProfile.jsx
- client/src/Components/UserInfo/UserPost.jsx
- client/src/Components/UserInfo/UserPostPagination.jsx
현재 로그아웃과 회원 탈퇴는 같게 진행이 되며 회원 탈퇴는 백엔드에서 API 완성 되면 연동해서 추가로 올리겠습니다.
> [FE] feat: [UserInfo] 로그아웃, 회원탈퇴 기능 구현

- client/src/Components/Header/Header.jsx
- client/src/Components/UserInfo/UserCardProfile.jsx
- client/src/Pages/Login/Login.jsx
- client/src/Pages/Review/Review.jsx
- client/src/Pages/Signup/Signup.jsx
- client/src/Style/GreetingInfo.js
- client/src/Style/ServiceInfoStyle.js
- feat:MEMBER_STATUS - MEMBER_QUIT 으로 변경으로 회원 탈퇴 구현
> feat:MEMBER_STATUS - MEMBER_QUIT 으로 변경으로 회원 탈퇴 구현

- client/src/Components/HospitalLocation/HospitalLocation.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- feat:HospitalLocation 컴포넌트- 기능 구현 #91
> feat:HospitalLocation 컴포넌트- 기능 구현 #91

- client/src/Pages/Login/Login.jsx
- feat:Enter key를 이용한 로그인 폼 제출 구현 #16
> [FE] feat:Enter key를 이용한 로그인 폼 제출 구현 #16

- client/src/Components/UserInfo/EditUserInfo.jsx
- client/src/Components/UserInfo/UserMainProfile.jsx
- client/src/Pages/Admin/Admin.jsx
- client/src/Pages/DoctorSignup/DoctorSignup.jsx
- client/src/Pages/Signup/Signup.jsx
- feat: 관리자 페이지 생성, EditUserInfo 컴포넌트 생성 및 수정 기능 구현 확인
> [FE] feat: 관리자 페이지 생성, EditUserInfo 컴포넌트 생성 및 수정 기능 구현

- client/src/Components/Answers/Answers.jsx
- client/src/Components/MakeContents/MakeContents.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Style/QuestionDetailStyle.js
* 질문 및 댓글 내 좋아요 기능 중복 사용 시 중복이라는 경고 창이 렌더링되는 기능을 구현했습니다.
* 해당 파일 및 다른 몇몇 파일에서 중복코드 및 불필요한 코드를 제거했습니다.
> [FE] feat: 질문 및 댓글 내 좋아요 기능 중복 사용 방지를 위한 error handling 코드 작성, 불필요한 코드 제거 및 중복 코드 제거

- client/src/App.js
- client/src/Components/Answers/Answers.jsx
- client/src/Components/Nav/LocationButton.jsx
- client/src/Components/Nav/Nav.jsx
- client/src/Components/Nav/TypeButton.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/Review/Review.jsx
- client/src/Style/AskQuestionStyle.js
- client/src/Style/NavStyle.js
- client/src/Style/QuestionDetailStyle.js
- client/src/Style/ReviewDetailStyle.js
* Nav 컴포넌트 내 지역 및 진료과목 hover시 상세 목록 렌더링
* 질문/리뷰 상세 페이지 내 footer 항목과 section 겹치는 부분 수정
*  질문 페이지 내 글 및 댓글 작성자는 본인의 게시글 및 댓글에 좋아요 기능 비활성화
* Nav 컴포넌트 내 path는 추 후 수정하겠습니다.
> [FE] feat: Nav 컴포넌트 내 지역 및 진료과목 hover시 상세 목록 렌더링, 질문/리뷰 상세 페이지 내 footer 항목과 section 겹치는 부분 수정, 질문 페이지 내 글 및 댓글 작성자는 본인의 게시글 및 댓글에 좋아요 기능 비활성화

- client/src/Components/Answers/Answers.jsx
- client/src/Components/CommentForm/EditCommentForm.jsx
- client/src/Components/ReportModal/ReportComment.jsx
- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
* 좋아요, 채택, 수정, 댓글작성 시 새로고침 대신 해당 부분만 재 렌더링 되도록 수정
* 페이지 내 각종 path값 수정
> [FE] fix: 좋아요, 채택, 수정, 댓글작성 시 새로고침 대신 해당 부분만 재 렌더링 되도록 수정,페이지 내 각종 path값 수정

- client/src/Components/Answers/Answers.jsx
- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/EditQuestion/EditQuestion.jsx
- client/src/Pages/Review/Review.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- client/src/Style/QuestionDetailStyle.js
* 댓글 좋아요 및 리뷰 게시글 좋아요 누를 시 새로고침 대신 해당 부분만 리렌더링하게 코드 수정
* 비로그인 및 권한이 없을 경우 경고 창 모달로 구현
* 질문 게시글 수정 시 알람 모달로 구현
* 본인 게시글에 좋아요 누를 시 경고창 모달로 구현
> [FE] fix: 각종 기능 실행 시 새로고침 대신 해당 부분만 리렌더링하게 기능 수정, UX향상을 위해 모달창 구현

- client/src/Components/Login/GoolgeButton.jsx
- client/src/util/Token.js
- feat : 엑세스 토큰 검증해서 유요한 토큰 값 리턴하는 hook 생성
과연 엑세스 토큰 갱신과 소셜 로그인 둘 다 잡을 수 있을까..?
> [FE] feat : 엑세스 토큰 검증해서 유요한 토큰 값 리턴하는 hook 생성

- client/src/Components/Answers/Answers.jsx
- client/src/Components/AskForm/TextEditor.jsx
- client/src/Components/CommentForm/CommentForm.jsx
- client/src/Components/ReportModal/ReportComment.jsx
- client/src/Components/ReviewForm/RateStar.jsx
- client/src/Pages/EditQuestion/EditQuestion.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- client/src/Style/QuestionDetailStyle.js
- client/src/Style/ReviewDetailStyle.js
* 게시글 상세 페이지 접근 시 비로그인 상태일 경우 경고창과 함께 로그인 화면으로 이동하도록 기능 구현
* textEditor를 이용하여 게시글 생성 시 html태그와 같이 생성되는 오류 수정
* 채택된 댓글이 있을경우 해당 게시글, 해당 댓글 및 타 댓글들 수정 불가 하도록 기능 구현
* 본인 게시글 좋아요 누를 시 실패 알람창 구현
> [FE] fix: 각 페이지 내 유효성 검사 추가 및 UX향상을 위한 각종 경고창 및 모달 창 구현

- client/package.json
- client/src/Style/CommentFormStyle.js
- chore:html-react-parser 라이브러리 설치 
클론 받아서 실행하니까 라이브러리 미설치로 에러떠서 바로 PR 날립니다~!
CommentFormStyle.js에  SVaildFail 이 없어서 에러 뜨길래 검색해서 동일한 이름의 스타일 복붙했습니다~!
확인하시고 스타일 다르면 수정 부탁드릴게요~!
> [FE] chore:html-react-parser 라이브러리 설치

- client/public/index.html
- client/src/Components/HospitalLocation/HospitalLocation.jsx
- client/src/Components/Section/PostList.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- feat : 질문, 리뷰 각 게시글 상세 페이지로 이동 
- style : 리뷰 상세 페이지 지도 이용을 위한 주석 해제
주석 해제 되어서 로컬에서 작업하는 동안은 www 붙여서 www.localhost:3000 으로 접속하셔야 확인 가능합니다~!
env 설정도 필수~!
> [FE] feat : 질문, 리뷰 각 게시글 상세 페이지로 이동 

- client/src/Pages/home/LocationPosts.jsx
> [FE] 지역 리스트 경로 path 값 누락 수정

- client/src/Components/Answers/Answers.jsx
- client/src/Components/CommentForm/CommentForm.jsx
- client/src/Components/CommentForm/EditCommentForm.jsx
- client/src/Components/ReportModal/ReportComment.jsx
- client/src/Components/ReportModal/ReportModal.jsx
- client/src/Components/UserInfo/EditUserInfo.jsx
- client/src/Components/UserInfo/UserCardProfile.jsx
- client/src/Components/UserInfo/UserInfo.jsx
- client/src/Components/UserInfo/UserPostPagination.jsx
- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/EditQuestion/EditQuestion.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/Review/Review.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- client/src/util/Token.js
* getAccessTokenFromLocal Hook을 이용하여 Accesstoken 사용하도록 코드 수정하였습니다
* access 토큰 사용하는 곳은 해당 훅 사용하도록 다 바꿔버렸습니다.
> [FE]  feat: getAccessTokenFromLocal Hook을 이용하여 Accesstoken 사용하도록 코드 수정

- client/src/Components/Section/PostPagination.jsx
- client/src/Components/UserInfo/UserInfo.jsx
- client/src/Components/UserInfo/UserPostPagination.jsx
- client/src/Style/PostListStyle.js
- client/src/Style/PostPaginationStyle.js
- client/src/util/Token.js
> [FE] 만료 토큰 갱신 훅 수정 및 페이지네이션 기능 구현 수정

- client/src/Style/NavStyle.js
- client/src/Style/PostCategoryStyle.js
- client/src/Style/PostPaginationStyle.js
- client/src/Style/PostTopicStlye.js
- client/src/Style/QuestionDetailStyle.js
- client/src/Style/ReviewDetailStyle.js
- client/src/Style/SectionStyle.js
- client/src/Style/UserCardProfileStyle.js
- client/src/Style/UserInfoStyle.js
- client/src/Style/UserMainProfileStyle.js
- client/src/Style/UserPostCategoryStyle.js
* 전체적인 페이지 내 폰트 스타일 및 배경색 통일화 하였습니다.
> [FE] style: 전체 페이지 내 폰트 및 배경색 통일화

- client/public/index.html
- client/src/Components/Answers/Answers.jsx
- client/src/Components/CommentForm/CommentForm.jsx
- client/src/Components/Header/Header.jsx
- client/src/Components/HospitalLocation/HospitalLocation.jsx
- client/src/Components/Nav/TypeButton.jsx
- client/src/Components/ReportModal/ReportModal.jsx
- client/src/Components/Section/PostList.jsx
- client/src/Components/Section/PostPagination.jsx
- client/src/Components/UserInfo/UserCardProfile.jsx
- client/src/Components/UserInfo/UserInfo.jsx
- client/src/Pages/DoctorSignup/DoctorSignup.jsx
- client/src/Pages/EditQuestion/EditQuestion.jsx
- client/src/Pages/Login/Login.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- client/src/Pages/Signup/Signup.jsx
- client/src/Pages/home/LocationPosts.jsx
- fix: 지역구, 과목별 내 페이지 이동 안되는 것 수정
- style : 불필요한 주석 및 콘솔 로그 삭제
> [FE] fix: 지역구, 과목별 내 페이지 이동 안되는 것 수정

- client/src/Components/Section/Section.jsx
- client/src/Components/UserInfo/UserInfo.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- client/src/Style/ReviewDetailStyle.js
* 리뷰 페이지 질문 페이지와 동일하게 스타일 조정하였습니다.
* 각 페이지 배경색도 통일화 하였습니다.
> style: 각 페이지 배경색 통일화 및 리뷰 페이지 스타일 수정

- client/package.json
- client/src/Components/Answers/Answers.jsx
- client/src/Components/CommentForm/CommentForm.jsx
- client/src/Components/CommentForm/EditCommentForm.jsx
- client/src/Components/MakeContents/MakeContents.jsx
- client/src/Components/ReportModal/ReportComment.jsx
- client/src/Components/ReportModal/ReportModal.jsx
- client/src/Components/Section/PostList.jsx
- client/src/Components/Section/PostPagination.jsx
- client/src/Components/Section/PostSearch.jsx
- client/src/Components/UserInfo/EditUserInfo.jsx
- client/src/Components/UserInfo/UserCardProfile.jsx
- client/src/Components/UserInfo/UserInfo.jsx
- client/src/Components/UserInfo/UserPostPagination.jsx
- client/src/Pages/Admin/Admin.jsx
- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/DoctorSignup/DoctorSignup.jsx
- client/src/Pages/EditQuestion/EditQuestion.jsx
- client/src/Pages/Login/Login.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/Pages/Review/Review.jsx
- client/src/Pages/ReviewDetail/ReviewDetail.jsx
- client/src/Pages/Signup/Signup.jsx
- client/src/Style/SectionStyle.js
- client/src/util/Token.js
> [FE] fix : 배포 환경에 맞춰 경로 설정

- client/src/Pages/AskQuestion/AskQuestion.jsx
- client/src/Pages/EditQuestion/EditQuestion.jsx
- client/src/Pages/Review/Review.jsx
> [FE] feat: 글 작성 도중 취소 버튼 누를 시 홈페이지 및 해당 게시글 페이지로 이동하도록 기능 구현

- client/src/Components/ScrollUp/ScrollUp.jsx
- client/src/Pages/QuestionDetail/QuestionDetail.jsx
- client/src/index.js
* 페이지 이동 시 스크롤 최 상단으로 이동시키는 기능 추가
* 코드 내 오타 수정
> [FE] feat: 페이지 이동 시 스클로 최 상단으로 이동시키는 기능 추가, 코드 내 오타 수정

- client/src/Pages/Admin/Admin.jsx
- client/src/Style/AdminStyle.js
- client/src/Style/DoctorSignupStyle.js
- client/src/Style/HeaderStyle.js
- client/src/Style/LoginStyle.js
- client/src/Style/ServiceInfoStyle.js
- client/src/Style/SignupStyle.js
- feat : Admin 페이지 - 회원 삭제, 삭제글 삭제, 댓글 삭제 기능 구현
> [FE] feat : Admin 페이지 - 회원 삭제, 삭제글 삭제, 댓글 삭제 기능 구현

- client/src/Components/Header/Header.jsx
- client/src/Components/Landing/GreetingInfo.jsx
- client/src/Components/Nav/LocationButton.jsx
- client/src/Components/Nav/Nav.jsx
- client/src/Components/Nav/TypeButton.jsx
- client/src/Components/Section/PostPagination.jsx
- client/src/Components/Section/PostSearch.jsx
- client/src/Components/Section/PostTopic.jsx
- client/src/Style/FooterStyle.js
- client/src/Style/GreetingInfo.js
- client/src/Style/HeaderStyle.js
- client/src/Style/LoginStyle.js
- client/src/Style/OfferInfoStyle.js
- client/src/Style/PostPaginationStyle.js
- client/src/Style/SectionStyle.js
- client/src/Style/ServiceInfoStyle.js
> [FE] update: CSS 및 기능 수정 / 삭제

- client/src/Style/AskQuestionStyle.js
* 게시글 작성 페이지 내 높이 값 조절하는 짜잘한 풀리 날립니다!
> [FE] style: 게시글 작성 페이지 내 높이 값 조절

- client/public/index.html
- client/src/Style/HeaderStyle.js
[FE] style:index.html-description 수정
> [FE] style:index.html-description 수정
